name: Run fal scripts
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout before downloading artifacts or setting profiles.yml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: fal-ai/dbt-cloud-action@main
        id: dbt_cloud_run
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
          dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}
          interval: 5
          failure_on_error: false

          cause: "Some cause"
          git_sha: ${{ github.sha }}
          # git_branch:
          # schema_override:
          # dbt_version_override:
          threads_override: 1
          # target_name_override:
          generate_docs_override: false
          # timeout_seconds_override:
          steps_override: |
            - dbt seed
            - dbt run

      - name: Setup profiles.yml
        shell: python
        env:
          contents: ${{ secrets.PROFILES_YML }}
        run: |
          import yaml
          import os
          import io

          profiles_string = os.getenv('contents')
          profiles_data = yaml.safe_load(profiles_string)

          with io.open('profiles.yml', 'w', encoding='utf8') as outfile:
            yaml.dump(profiles_data, outfile, default_flow_style=False, allow_unicode=True)

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: pip install --upgrade --upgrade-strategy eager -r requirements.txt

      - name: Run fal scripts
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        run: |
          # Move to the same code state of the dbt Cloud Job
          echo "Run id: ${{ steps.dbt_cloud_run.outputs.run_id }}"
          git checkout ${{ steps.dbt_cloud_run.outputs.git_sha }}
          fal run --profiles-dir .
